"use strict";
exports.__esModule = true;
var StudentController_1 = require("./controllers/StudentController");
var StudentView_1 = require("./views/StudentView");
var divisor = '-'.repeat(40);
var greeting = divisor + "\nSistema escolar inicializado.\n" + divisor;
console.log(greeting);
console.log(StudentController_1["default"].listStudents());
console.log(divisor);
console.log(StudentController_1["default"].addStudent(''));
console.log(StudentController_1["default"].addStudent('    '));
console.log(StudentController_1["default"].addStudent('John Doe'));
console.log(divisor);
var student1 = StudentController_1["default"].findStudent('');
console.log(student1);
var student2 = StudentController_1["default"].findStudent('John');
console.log(StudentView_1["default"](student2));
console.log(divisor);
student2 = StudentController_1["default"].enrollStudent(student2, 'Typescript 101');
console.log(StudentView_1["default"](student2));
console.log(divisor);
student2 = StudentController_1["default"].addAbsence(student2);
console.log(StudentView_1["default"](student2));
console.log(divisor);
var student3 = StudentController_1["default"].addGrade(student2, -1.8);
console.log(student3);
var student4 = StudentController_1["default"].addGrade(student2, 10.8);
console.log(student4);
student2 = StudentController_1["default"].addGrade(student2, 1.8);
console.log(StudentView_1["default"](student2));
console.log(divisor);
console.log(StudentController_1["default"].flunkOrPass(student2));
student2 = StudentController_1["default"].addGrade(student2, 10);
student2 = StudentController_1["default"].addGrade(student2, 8);
student2 = StudentController_1["default"].addGrade(student2, 9);
console.log(StudentController_1["default"].flunkOrPass(student2));
student2 = StudentController_1["default"].addAbsence(student2);
student2 = StudentController_1["default"].addAbsence(student2);
student2 = StudentController_1["default"].addAbsence(student2);
console.log(StudentController_1["default"].flunkOrPass(student2));
console.log(divisor);
