"use strict";
exports.__esModule = true;
var StudentController_1 = require("./controllers/StudentController");
var StudentViews_1 = require("./views/StudentViews");
var divisor = '-'.repeat(40);
var greeting = divisor + "\nSistema escolar inicializado\n" + divisor;
console.log(greeting);
console.log(StudentController_1["default"].listStudents());
console.log(divisor);
console.log(StudentController_1["default"].addStudent(''));
console.log(StudentController_1["default"].addStudent('    '));
console.log(StudentController_1["default"].addStudent('John Doe'));
console.log(divisor);
var student1 = StudentController_1["default"].findStudent('');
console.log(student1);
var student2 = StudentController_1["default"].findStudent('John');
console.log(StudentViews_1["default"](student2));
console.log(divisor);
